### ISSUE TITLE
Trying to convert from Pointcloud2Msg to r2r::msg::PointCloud2

### ISSUE THREAD

**Issue by TheMotonaut** [stelzo/ros_pointcloud2#21]
Hi

Im trying publish a PointCloud2 message in the r2r library, but I am having trouble getting it to compile correctly.

    let msg = PointCloud2Msg::try_from_iter(xyz).unwrap();

    let r2r_msg: PointCloud2= msg.into();

    publisher.publish(&r2r_msg).unwrap();

xyz is a vector with PointXYZ types. When I compile I get the error:

    error[E0277]: the trait bound `PointCloud2: From<ros_pointcloud2::PointCloud2Msg>` is not satisfied
    let r2r_msg: PointCloud2= msg.into();
    ^^^^ the trait `From<ros_pointcloud2::PointCloud2Msg>` is not implemented for `PointCloud2`

I have imported 
use ros_pointcloud2::prelude::*;
use r2r::{
    QosProfile, sensor_msgs::msg::PointCloud2,
};

I am using 0.5.0-rc.1 since there were going to be so many changes anyway.

Im a new to Rust so I am not sure what exactly I am doing wrong
Thank you!

**Comment by stelzo** [comment]
Hi!

Did you activate the `r2r_msg` feature? The missing implementation is behind a feature flag, which needs to be specified in your import inside the `Cargo.toml` file like this:
```
ros_pointcloud2 = { version = "0.5.0-rc.1", features = ["r2r_msg"] }
```

A full list of features can be found in the [docs](https://docs.rs/ros_pointcloud2/0.5.0-rc.1/ros_pointcloud2/#features).

Since you said you are new to Rust, I think that could be the problem. Every library has the ability to give features that are mostly additive, so you could add `rayon` in there as well for parallel processing.

**Comment by TheMotonaut** [comment]
The feature is active
I thought it might had something to do with #[cfg(feature = "r2r_msg")] but this removes the next line from the scope so no luck

**Comment by stelzo** [comment]
Ok, I don't know enough about your code to see what happened. Could you share more? You also can compare it with the [r2r CI test](https://github.com/stelzo/ros_pointcloud2/blob/main/rpcl2/tests/r2r_msg_test.rs).

**Comment by TheMotonaut** [comment]
I found the problem!

The problem was that the version imported by cargo for r2r was 9.0.0, I had not specified a certain version, and the dependency for ros_pointcloud2 was 0.8.4 so something weird happend there-

**Comment by stelzo** [comment]
I just had the same problem with a different tool ([tf_r2r](https://github.com/smilerobotics/tf_rosrust/tree/main/tf_r2r) in a node of mine and thought this package will have the same problem for diverging major versions.

Since the message types are highly likely to not change over time. I could do some macro things here, but that would still be hacky and don't assure compatibility. I think a better solution would be for the ROS client implementations to depend on a centralized message crate(s) for the system messages. Then we could have tooling regardless of the ROS library. This is also discussed [here](https://github.com/ros2-rust/ros2_rust/issues/394).

For now, I'll update the dependency to the newest version. You can change to `0.5.0-rc.3` for `r2r` 0.9 if you need that.

**Comment by TheMotonaut** [comment]
Cool thank you
